=== kjbranch/z3-json-data/schema/z3-room.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "z3-room.schema.json",
  "type": "object",
  "description": "A contiguous area in Link to the Past.",
  "required": [
    "id",
    "name",
    "roomType",
    "nodes",
    "strats"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "integer",
      "minimum": 0
    },
    "name": {
      "type": "string"
    },
    "roomType": {
      "type": "string",
      "enum": [
        "Cave",
        "Dungeon",
        "House",
        "Overworld"
      ]
    },
    "note": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "alttpEntrandoRegions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "name": {
            "type": "string"
          },
          "nodeType": {
            "type": "string",
            "enum": [
              "boss",
              "door",
              "drop",
              "entrance",
              "event",
              "exit",
              "fortune",
              "item",
              "junction",
              "minigame",
              "obstacle",
              "shop",
              "transition"
            ]
          },
          "area": {
            "type": "string"
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark",
              "both"
            ]
          },
          "entrances": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "world"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "integer",
                  "minimum": 1
                },
                "name": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "transitions": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "edge",
                "span"
              ],
              "additionalProperties": false,
              "properties": {
                "edge": {
                  "type": "string",
                  "enum": [
                    "north",
                    "south",
                    "east",
                    "west"
                  ]
                },
                "span": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": {
                    "type": "number"
                  }
                },
                "terrain": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "teleports": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "world"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "integer",
                  "minimum": 1
                },
                "name": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "nodeItem": {
            "type": "string"
          },
          "nodeAddress": {
            "type": [
              "string",
              "array"
            ],
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "requires": {
            "type": "array",
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "locks": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "type": "object",
              "required": [
                "lockType",
                "unlock"
              ],
              "additionalProperties": false,
              "properties": {
                "lockType": {
                  "type": "string",
                  "enum": [
                    "bossFight",
                    "cutscene",
                    "gameFlag",
                    "killEnemies",
                    "lockedDoor",
                    "permanent",
                    "triggeredEvent"
                  ]
                },
                "lock": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "$ref": "z3-requirement.schema.json"
                  }
                },
                "unlock": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "$ref": "z3-requirement.schema.json"
                  }
                },
                "note": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "view": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "yields": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "locationName",
          "itemLocation",
          "item",
          "itemAddress"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "locationName": {
            "type": "string"
          },
          "itemLocation": {
            "type": "integer",
            "minimum": 1
          },
          "item": {
            "type": "string"
          },
          "itemAddress": {
            "type": [
              "string",
              "array"
            ],
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "lockedDoors": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "locationName",
          "doorPosition",
          "doorLocation",
          "keyType"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "locationName": {
            "type": "string"
          },
          "doorPosition": {
            "type": "string",
            "enum": [
              "north",
              "south",
              "east",
              "west",
              "middle"
            ]
          },
          "doorLocation": {
            "type": "integer",
            "minimum": 1
          },
          "keyType": {
            "type": "string",
            "enum": [
              "big",
              "small",
              "bomb",
              "bomb, boots",
              "boots"
            ]
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          }
        }
      }
    },
    "obstacles": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "note"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "strats": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "link",
          "name",
          "requires"
        ],
        "additionalProperties": false,
        "properties": {
          "link": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "name": {
            "type": "string"
          },
          "requires": {
            "type": "array",
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "notable": {
            "type": "boolean"
          },
          "collectsItems": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "setsFlags": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "clearsObstacles": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "unlocksDoor": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark",
              "any"
            ]
          },
          "fromWorld": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "toWorld": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "isBunny": {
            "type": "string",
            "enum": [
              "yes",
              "no",
              "any"
            ]
          },
          "setsFollower": {
            "type": "string",
            "enum": [
              "None",
              "Zelda",
              "Old Man",
              "Blind",
              "Dwarf",
              "Purple Chest",
              "Big Bomb"
            ]
          },
          "FollowerComplete": {
            "type": "string",
            "enum": [
              "Zelda",
              "Old Man",
              "Blind",
              "Dwarf",
              "Purple Chest",
              "Big Bomb"
            ]
          },
          "exitState": {
            "type": "object",
            "required": [
              "state",
              "type"
            ],
            "additionalProperties": false,
            "properties": {
              "state": {
                "type": "string",
                "enum": [
                  "event"
                ]
              },
              "type": {
                "type": "string"
              }
            }
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "allOf": [
    {
      "if": {
        "required": [
          "roomType"
        ],
        "properties": {
          "roomType": {
            "const": "Overworld"
          }
        }
      },
      "then": {
        "properties": {
          "nodes": {
            "items": {
              "required": [
                "world"
              ]
            }
          },
          "strats": {
            "items": {
              "oneOf": [
                {
                  "required": [
                    "world"
                  ]
                },
                {
                  "required": [
                    "fromWorld",
                    "toWorld"
                  ]
                }
              ]
            }
          }
        }
      },
      "else": {
        "properties": {
          "nodes": {
            "items": {
              "required": [
                "nodeType"
              ]
            }
          }
        }
      }
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/1E Eastern Palace.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 20,
  "name": "Eastern Palace",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Southern Half",
      "world": "both",
      "transitions": [
        {"edge": "south", "span": [7, 10]},
        {"edge": "south", "span": [55, 57]}
      ],
      "entrances": [
        {
          "id": 1,
          "name": "Palace of Darkness Cottage",
          "world": "dark"
        }
      ]
    },
    {
      "id": 2,
      "name": "Northwest Area",
      "world": "light",
      "entrances": [
        {
          "id": 1,
          "name": "Sahasrahla's Hut",
          "world": "light"
        }
      ]
    },
    {
      "id": 3,
      "name": "Northeast Dungeon Entrance",
      "world": "light",
      "entrances": [
        {
          "id": 1,
          "name": "Eastern Palace Entrance",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Palace of Darkness Entrance",
          "world": "dark"
        }
      ]
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [1, 2],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"or": [
          {"sword": 1},
          "Boomerang",
          "Hookshot",
          {"arrows": 2},
          {"silverArrows": 1},
          {"rod": 1},
          {"combatProficiency": 2},
          {"damage": {"enemy": "Ropa", "count": 1}}
        ]}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"or": [
          {"sword": 1},
          "Boomerang",
          "Hookshot",
          {"arrows": 4},
          {"silverArrows": 2},
          {"rod": 2},
          {"combatProficiency": 2},
          {"damage": {"enemy": "Ropa", "count": 2}}
        ]}
      ]
    },
    {
      "link": [2, 3],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [2, 3],
      "name": "Pay Kiki",
      "world": "dark",
      "requires": [
        {"follower": "None"},
        {"pay": 110}
      ],
      "setsFlags": ["OpenedPalaceOfDarkness"],
      "devNote": ["Kiki cannot leave the room, so there isn't much need to use a Kiki follower object to represent unlocking the dungeon."]
    },
    {
      "link": [2, 3],
      "name": "Base - Already Opened",
      "world": "dark",
      "requires": [
        {"flag": "OpenedPalaceOfDarkness"}
      ]
    },
    {
      "link": [3, 2],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [3, 2],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"or": [
          {"sword": 1},
          "Boomerang",
          "Hookshot",
          {"arrows": 2},
          {"silverArrows": 1},
          {"rod": 1},
          {"combatProficiency": 2},
          {"damage": {"enemy": "Ropa", "count": 1}}
        ]}
      ]
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/2F East Warp Point.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 30,
  "name": "East Warp Point",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Main Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [23, 25]}
      ],
      "entrances": [
        {
          "id": 1,
          "name": "Long Fairy Cave",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Dark East Portal Cave",
          "world": "dark"
        }
      ]
    },
    {
      "id": 2,
      "name": "Hammer Fence Circle",
      "world": "both"
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "any",
      "requires": [
        "Hammer"
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "any",
      "requires": [
        "Hammer"
      ]
    },
    {
      "link": [2, 2],
      "fromWorld": "light",
      "toWorld": "dark",
      "name": "Dark World Portal",
      "requires": [
        {"glove": 1}
      ]
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/32 Cave 45.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 32,
  "name": "Cave 45",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Main Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [3, 7.5]},
        {"edge": "east", "span": [5.5, 29]}
      ]
    },
    {
      "id": 2,
      "name": "North Bush Blocked Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [13.5, 16.5]}
      ]
    },
    {
      "id": 3,
      "name": "Cave 45 Ledge",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Cave 45 Entrance",
          "world": "light"
        }
      ]
    }
  ],
  "strats": [
    {
      "link": [1, 1],
      "name": "Bonk Fairy",
      "world": "light",
      "requires": [
        "PegasusBoots",
        {"refill": {"type": "Fairy", "limit": 1}}
      ],
      "note": ["The southeast tree will release a fairy when dashed into."]
    },
    {
      "link": [1, 2],
      "name": "Base",
      "world": "any",
      "requires": [
        {"glove": 0}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "any",
      "requires": [
        {"glove": 0}
      ]
    },
    {
      "link": [1, 3],
      "name": "Base",
      "world": "dark",
      "requires": []
    }
  ]
}

=== kjbranch/z3-json-data/rooms/caves/light/0A Old Man Cave.json
{
  "$schema": "../../../schema/z3-room.schema.json",
  "id": 11,
  "name": "Old Man Cave",
  "roomType": "Cave",
  "nodes": [
    {
      "id": 1,
      "name": "Mountain Entrance Side",
      "nodeType": "door"
    },
    {
      "id": 2,
      "name": "Death Mountain Side",
      "nodeType": "door"
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "requires": [
        "Lamp"
      ],
      "setsFollower": "Old Man"
    },
    {
      "link": [1, 2],
      "name": "Darkness",
      "requires": [
        {"darkProficiency": 2},
        {"or": [
          {"and": [
            {"sword": 1},
            {"damage": {"enemy": "Fall", "count": 1}}
          ]},
          {"and": [
            {"darkProficiency": 3},
            {"sword": 1}
          ]},
          {"and": [
            {"darkProficiency": 3},
            {"damage": {"enemy": "Fall", "count": 1}},
            {"damage": {"enemy": "Keese", "count": 1}}
          ]}
        ]}
      ],
      "setsFollower": "Old Man"
    },
    {
      "link": [1, 2],
      "name": "Darkness - Item Use Audio",
      "requires": [
        {"darkProficiency": 3},
        {"damage": {"enemy": "Keese", "count": 1}},
        {"or": [
          "BookOfMudora",
          "Bombos",
          "Ether",
          "Quake",
          "Shovel",
          "BugCatchingNet",
          "PegasusBoots",
          "Bottle",
          "FireRod",
          "IceRod",
          "Bow",
          "Powder",
          "RedCane",
          "BlueCane",
          "Cape",
          {"and": [
            "Mushroom",
            "canRiskPermanentLossOfAccess"
          ]}
        ]}
      ],
      "devNote": [
        "Nearly any item can get through here with using the audio or visual cue to determine when Link goes through the door to prevent falling into the pit.",
        "Because it's nearly every item, but some would drain Link's resources, this is just listed as free.",
        "FIXME: Add a way to represent each item drains its resourse: i.e. magic, arrows, empty bottle.",
        "It's neglected for now due to schema limitations and because it only saves one heart.",
        "Note that the medallions don't need to drain magic, unless they're changed to be usable without a sword."
      ],
      "setsFollower": "Old Man"
    },
    {
      "link": [2, 2],
      "name": "Base",
      "requires": [
        "Lamp"
      ],
      "setsFollower": "Old Man"
    },
    {
      "link": [2, 2],
      "name": "Darkness",
      "requires": [
        {"darkProficiency": 2},
        {"or": [
          {"and": [
            {"sword": 1},
            {"damage": {"enemy": "Fall", "count": 1}}
          ]},
          {"and": [
            {"darkProficiency": 3},
            {"sword": 1}
          ]},
          {"and": [
            {"darkProficiency": 3},
            {"damage": {"enemy": "Keese", "count": 3}},
            {"damage": {"enemy": "Fall", "count": 1}}
          ]}
        ]}
      ],
      "setsFollower": "Old Man"
    },
    {
      "link": [2, 2],
      "name": "Darkness - Item Use Audio",
      "requires": [
        {"darkProficiency": 3},
        {"damage": {"enemy": "Keese", "count": 3}},
        {"or": [
          "BookOfMudora",
          "Bombos",
          "Ether",
          "Quake",
          "Shovel",
          "BugCatchingNet",
          "PegasusBoots",
          "Bottle",
          "FireRod",
          "IceRod",
          "Bow",
          "Powder",
          "RedCane",
          "BlueCane",
          "Cape",
          {"and": [
            "Mushroom",
            "canRiskPermanentLossOfAccess"
          ]}
        ]}
      ],
      "devNote": [
        "Nearly any item can get through here with using the audio or visual cue to determine when Link goes through the door to prevent falling into the pit.",
        "Because it's nearly every item, but some would drain Link's resources, this is just listed as free.",
        "FIXME: Add a way to represent each item drains its resourse: i.e. magic, arrows, empty bottle.",
        "It's neglected for now due to schema limitations and because it only saves one heart.",
        "Note that the medallions don't need to drain magic, unless they're changed to be usable without a sword."
      ],
      "setsFollower": "Old Man"
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/2A Haunted Grove.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 25,
  "name": "Haunted Grove",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Main Area",
      "world": "both",
      "transitions": [
        {"edge": "south", "span": [13.5, 16.5]}
      ]
    },
    {
      "id": 2,
      "name": "Southwest Area",
      "world": "both",
      "transitions": [
        {"edge": "south", "span": [3, 7.5]},
        {"edge": "west", "span": [22.5, 27.5]}
      ]
    }
  ],
  "items": [
    {
      "id": 1,
      "locationName": "Grove Dig Spot",
      "itemLocation": 1,
      "world": "light",
      "item": "OcarinaInactive",
      "itemAddress": "0x18014A"
    },
    {
      "id": 2,
      "locationName": "Stumpy's Gift",
      "itemLocation": 1,
      "world": "dark",
      "item": "Shovel",
      "itemAddress": "0x330C7"
    }
  ],
  "strats": [
    {
      "link": [1, 1],
      "name": "Dig",
      "world": "light",
      "requires": [
        "Shovel"
      ],
      "collectsItems": [1]
    },
    {
      "link": [1, 1],
      "name": "Stumpy",
      "world": "dark",
      "requires": [],
      "collectsItems": [2]
    }
  ]
}
