=== kjbranch/z3-json-data/schema/z3-room.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "z3-room.schema.json",
  "type": "object",
  "description": "A contiguous area in Link to the Past.",
  "required": [
    "id",
    "name",
    "roomType",
    "nodes",
    "strats"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "integer",
      "minimum": 0
    },
    "name": {
      "type": "string"
    },
    "roomType": {
      "type": "string",
      "enum": [
        "Cave",
        "Dungeon",
        "House",
        "Overworld"
      ]
    },
    "note": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "alttpEntrandoRegions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "name": {
            "type": "string"
          },
          "nodeType": {
            "type": "string",
            "enum": [
              "boss",
              "door",
              "drop",
              "entrance",
              "event",
              "exit",
              "fortune",
              "item",
              "junction",
              "minigame",
              "obstacle",
              "shop",
              "transition"
            ]
          },
          "area": {
            "type": "string"
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark",
              "both"
            ]
          },
          "entrances": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "world"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "integer",
                  "minimum": 1
                },
                "name": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "transitions": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "edge",
                "span"
              ],
              "additionalProperties": false,
              "properties": {
                "edge": {
                  "type": "string",
                  "enum": [
                    "north",
                    "south",
                    "east",
                    "west"
                  ]
                },
                "span": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": {
                    "type": "number"
                  }
                },
                "terrain": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "teleports": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "world"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "integer",
                  "minimum": 1
                },
                "name": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "nodeItem": {
            "type": "string"
          },
          "nodeAddress": {
            "type": [
              "string",
              "array"
            ],
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "requires": {
            "type": "array",
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "locks": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "type": "object",
              "required": [
                "lockType",
                "unlock"
              ],
              "additionalProperties": false,
              "properties": {
                "lockType": {
                  "type": "string",
                  "enum": [
                    "bossFight",
                    "cutscene",
                    "gameFlag",
                    "killEnemies",
                    "lockedDoor",
                    "permanent",
                    "triggeredEvent"
                  ]
                },
                "lock": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "$ref": "z3-requirement.schema.json"
                  }
                },
                "unlock": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "$ref": "z3-requirement.schema.json"
                  }
                },
                "note": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "view": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "yields": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "locationName",
          "itemLocation",
          "item",
          "itemAddress"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "locationName": {
            "type": "string"
          },
          "itemLocation": {
            "type": "integer",
            "minimum": 1
          },
          "item": {
            "type": "string"
          },
          "itemAddress": {
            "type": [
              "string",
              "array"
            ],
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "lockedDoors": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "locationName",
          "doorPosition",
          "doorLocation",
          "keyType"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "locationName": {
            "type": "string"
          },
          "doorPosition": {
            "type": "string",
            "enum": [
              "north",
              "south",
              "east",
              "west",
              "middle"
            ]
          },
          "doorLocation": {
            "type": "integer",
            "minimum": 1
          },
          "keyType": {
            "type": "string",
            "enum": [
              "big",
              "small",
              "bomb",
              "bomb, boots",
              "boots"
            ]
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          }
        }
      }
    },
    "obstacles": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "note"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "strats": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "link",
          "name",
          "requires"
        ],
        "additionalProperties": false,
        "properties": {
          "link": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "name": {
            "type": "string"
          },
          "requires": {
            "type": "array",
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "notable": {
            "type": "boolean"
          },
          "collectsItems": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "setsFlags": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "clearsObstacles": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "unlocksDoor": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark",
              "any"
            ]
          },
          "fromWorld": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "toWorld": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "isBunny": {
            "type": "string",
            "enum": [
              "yes",
              "no",
              "any"
            ]
          },
          "setsFollower": {
            "type": "string",
            "enum": [
              "None",
              "Zelda",
              "Old Man",
              "Blind",
              "Dwarf",
              "Purple Chest",
              "Big Bomb"
            ]
          },
          "FollowerComplete": {
            "type": "string",
            "enum": [
              "Zelda",
              "Old Man",
              "Blind",
              "Dwarf",
              "Purple Chest",
              "Big Bomb"
            ]
          },
          "exitState": {
            "type": "object",
            "required": [
              "state",
              "type"
            ],
            "additionalProperties": false,
            "properties": {
              "state": {
                "type": "string",
                "enum": [
                  "event"
                ]
              },
              "type": {
                "type": "string"
              }
            }
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "allOf": [
    {
      "if": {
        "required": [
          "roomType"
        ],
        "properties": {
          "roomType": {
            "const": "Overworld"
          }
        }
      },
      "then": {
        "properties": {
          "nodes": {
            "items": {
              "required": [
                "world"
              ]
            }
          },
          "strats": {
            "items": {
              "oneOf": [
                {
                  "required": [
                    "world"
                  ]
                },
                {
                  "required": [
                    "fromWorld",
                    "toWorld"
                  ]
                }
              ]
            }
          }
        }
      },
      "else": {
        "properties": {
          "nodes": {
            "items": {
              "required": [
                "nodeType"
              ]
            }
          }
        }
      }
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/2E Lake Hylia Inlet.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 29,
  "name": "Lake Hylia Inlet",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Main Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [7, 10]},
        {"edge": "west", "span": [7, 13]}
      ],
      "entrances": [
        {
          "id": 1,
          "name": "Lake Hylia Inlet Great Fairy",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Ice Lake Inlet Great Fairy",
          "world": "dark"
        }
      ]
    },
    {
      "id": 2,
      "name": "South East Edge",
      "world": "both",
      "transitions": [
        {"edge": "south", "span": [25, 27]}
      ]
    },
    {
      "id": 3,
      "name": "River",
      "world": "both",
      "transitions": [
        {"edge": "south", "span": [19.5, 22.5], "terrain": "water"},
        {"edge": "west", "span": [16.5, 25], "terrain": "water"}
      ]
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"or": [
          {"sword": 1},
          "Boomerang",
          "Hookshot",
          {"arrows": 2},
          {"silverArrows": 1},
          {"rod": 1},
          {"combatProficiency": 2},
          {"damage": {"enemy": "Ropa", "count": 1}}
        ]}
      ]
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/03 Tower of Hera.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 3,
  "name": "Tower of Hera",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Mountain Entrance Cave",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Old Man Cave",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Dark Death Mountain Great Fairy",
          "world": "dark"
        }
      ]
    },
    {
      "id": 2,
      "name": "Old Man's House",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Old Man's House Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 3,
      "name": "Old Man's House Back Entrance",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Old Man's House Back Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 4,
      "name": "Lower East Edge",
      "world": "both",
      "transitions": [
        {"edge": "east", "span": [50, 56]}
      ]
    },
    {
      "id": 5,
      "name": "Long Staircase",
      "world": "dark",
      "entrances": [
        {
          "id": 1,
          "name": "Death Mountain Return Cave",
          "world": "light"
        }
      ]
    },
    {
      "id": 6,
      "name": "South of Spectacle Rock Peak",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Spectacle Rock Top Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 7,
      "name": "Dark World Portal",
      "world": "both"
    },
    {
      "id": 8,
      "name": "On Spectacle Rock Peak",
      "world": "both"
    },
    {
      "id": 9,
      "name": "Upper Main Area",
      "world": "both",
      "transitions": [
        {"edge": "east", "span": [7, 9]}
      ],
      "entrances": [
        {
          "id": 1,
          "name": "Tower of Hera Entrance",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Ganon's Tower Entrance",
          "world": "dark"
        }
      ]
    },
    {
      "id": 10,
      "name": "Left Balcony",
      "world": "light",
      "entrances": [
        {
          "id": 1,
          "name": "Spectacle Rock Bottom Left Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 11,
      "name": "Middle Balcony",
      "world": "light",
      "entrances": [
        {
          "id": 1,
          "name": "Spectacle Rock Bottom Right Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 12,
      "name": "Far Right Balcony",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Spike Cave Entrance",
          "world": "dark"
        }
      ]
    }
  ],
  "items": [
    {
      "id": 1,
      "locationName": "Rescue Old Man",
      "itemLocation": 2,
      "item": "MagicMirror",
      "itemAddress": "0xF69FA"
    },
    {
      "id": 2,
      "locationName": "Spectacle Rock Item",
      "itemLocation": 8,
      "world": "light",
      "item": "PieceOfHeart",
      "itemAddress": "0x180140"
    },
    {
      "id": 3,
      "locationName": "Ether Tablet",
      "itemLocation": 9,
      "world": "light",
      "item": "Ether",
      "itemAddress": "0x180016"
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "light",
      "requires": [
        {"or": [
          {"damage": {"enemy": "Deadrock", "count": 2}},
          {"and": [
            {"combatProficiency": 2},
            {"damage": {"enemy": "Deadrock", "count": 1}}
          ]},
          {"combatProficiency": 3}
        ]}
      ]
    },
    {
      "link": [1, 2],
      "name": "Invincibility",
      "world": "light",
      "requires": [
        {"combatProficiency": 2},
        {"or": [
          {"blueCane": 32},
          {"cape": 35}
        ]}
      ]
    },
    {
      "link": [1, 2],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "light",
      "requires": [
        {"or": [
          {"damage": {"enemy": "Deadrock", "count": 2}},
          {"and": [
            {"combatProficiency": 2},
            {"damage": {"enemy": "Deadrock", "count": 1}}
          ]},
          {"combatProficiency": 3}
        ]}
      ]
    },
    {
      "link": [2, 1],
      "name": "Invincibility",
      "world": "light",
      "requires": [
        {"combatProficiency": 2},
        {"or": [
          {"blueCane": 32},
          {"cape": 35}
        ]}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [2, 2],
      "name": "Rescue Old Man",
      "world": "light",
      "requires": [
        {"follower": "Old Man"}
      ],
      "collectsItems": [1],
      "FollowerComplete": "Old Man"
    },
    {
      "link": [2, 3],
      "name": "Base",
      "world": "light",
      "requires": [
        {"or": [
          {"damage": {"enemy": "Falling Boulder", "count": 1}},
          {"combatProficiency": 2}
        ]}
      ]
    },
    {
      "link": [2, 3],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [3, 2],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [3, 4],
      "name": "Base",
      "world": "light",
      "requires": [
        {"or": [
          {"damage": {"enemy": "Deadrock", "count": 2}},
          {"combatProficiency": 3}
        ]}
      ]
    },
    {
      "link": [3, 4],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [3, 5],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [4, 2],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [5, 1],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [5, 3],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [5, 6],
      "name": "Base",
      "world": "light",
      "requires": [
        {"or": [
          {"sword": 1},
          {"combatProficiency": 2},
          "h_NoAgahnimLoophole",
          {"arrows": 2},
          {"silverArrows": 2},
          {"rod": 2}
        ]}
      ]
    },
    {
      "link": [5, 6],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [5, 10],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [6, 5],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [6, 7],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [6, 8],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [6, 10],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [6, 11],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [7, 6],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [7, 12],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [8, 6],
      "name": "Base",
      "world": "dark",
      "requires": []
    },
    {
      "link": [8, 8],
      "name": "Base - Collect Item",
      "world": "light",
      "requires": [],
      "collectsItems": [2]
    },
    {
      "link": [8, 9],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [9, 5],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [9, 7],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [9, 9],
      "name": "Ether Tablet",
      "world": "light",
      "requires": [
        {"sword": 2},
        "BookOfMudora"
      ],
      "collectsItems": [3]
    },
    {
      "link": [10, 5],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [11, 5],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [12, 3],
      "name": "Base",
      "world": "any",
      "requires": []
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/1D Eastern Bridge.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 19,
  "name": "Eastern Bridge",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Southeast Area",
      "world": "both",
      "transitions": [
        {"edge": "south", "span": [4, 18]}
      ]
    },
    {
      "id": 2,
      "name": "Northeast Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [23, 27]}
      ]
    },
    {
      "id": 3,
      "name": "Northwest Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [4.5, 16]}
      ]
    },
    {
      "id": 4,
      "name": "River",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [18.5, 20.5], "terrain": "water"}
      ]
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "light",
      "requires": [
        {"glove": 0}
      ]
    },
    {
      "link": [1, 2],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"or": [
          "Hammer",
          {"glove": 1}
        ]}
      ]
    },
    {
      "link": [1, 3],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [1, 4],
      "name": "Base",
      "world": "dark",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "light",
      "requires": [
        {"glove": 0}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"or": [
          "Hammer",
          {"glove": 1}
        ]}
      ]
    },
    {
      "link": [2, 3],
      "name": "Base",
      "world": "dark",
      "requires": [
        "Hookshot"
      ]
    },
    {
      "link": [2, 4],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [3, 1],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [3, 4],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/33 Great Swamp Lake.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 33,
  "name": "Great Swamp Lake",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "West Main Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [8.5, 12]},
        {"edge": "west", "span": [5.5, 29]}
      ]
    },
    {
      "id": 2,
      "name": "East Main Area",
      "world": "both",
      "transitions": [
        {"edge": "east", "span": [8, 15]},
        {"edge": "east", "span": [21, 29]},
        {"edge": "south", "span": [10, 28]}
      ]
    },
    {
      "id": 3,
      "name": "Hammer Peg Blocked Teleporter",
      "world": "both"
    },
    {
      "id": 4,
      "name": "Lake",
      "world": "both",
      "transitions": [
        {"edge": "east", "span": [15, 21], "terrain": "water"}
      ],
      "teleports": [
        {
          "id": 1,
          "name": "Great Swamp Lake Whirlpool",
          "world": "light"
        }
      ]
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "any",
      "requires": [
        {"glove": 1}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "any",
      "requires": [
        {"glove": 1}
      ]
    },
    {
      "link": [2, 3],
      "name": "Base",
      "world": "any",
      "requires": [
        "Hammer"
      ]
    },
    {
      "link": [2, 4],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [3, 2],
      "name": "Base",
      "world": "any",
      "requires": [
        "Hammer"
      ]
    },
    {
      "link": [3, 3],
      "fromWorld": "light",
      "toWorld": "dark",
      "name": "Dark World Portal",
      "requires": [
        {"glove": 1}
      ]
    },
    {
      "link": [4, 2],
      "name": "Base",
      "world": "any",
      "requires": []
    }
  ]
}
