=== kjbranch/z3-json-data/schema/z3-room.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "z3-room.schema.json",
  "type": "object",
  "description": "A contiguous area in Link to the Past.",
  "required": [
    "id",
    "name",
    "roomType",
    "nodes",
    "strats"
  ],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "id": {
      "type": "integer",
      "minimum": 0
    },
    "name": {
      "type": "string"
    },
    "roomType": {
      "type": "string",
      "enum": [
        "Cave",
        "Dungeon",
        "House",
        "Overworld"
      ]
    },
    "note": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "alttpEntrandoRegions": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "nodes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "name"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "name": {
            "type": "string"
          },
          "nodeType": {
            "type": "string",
            "enum": [
              "boss",
              "door",
              "drop",
              "entrance",
              "event",
              "exit",
              "fortune",
              "item",
              "junction",
              "minigame",
              "obstacle",
              "shop",
              "transition"
            ]
          },
          "area": {
            "type": "string"
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark",
              "both"
            ]
          },
          "entrances": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "world"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "integer",
                  "minimum": 1
                },
                "name": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "transitions": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "edge",
                "span"
              ],
              "additionalProperties": false,
              "properties": {
                "edge": {
                  "type": "string",
                  "enum": [
                    "north",
                    "south",
                    "east",
                    "west"
                  ]
                },
                "span": {
                  "type": "array",
                  "minItems": 2,
                  "maxItems": 2,
                  "items": {
                    "type": "number"
                  }
                },
                "terrain": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "teleports": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "id",
                "name",
                "world"
              ],
              "additionalProperties": false,
              "properties": {
                "id": {
                  "type": "integer",
                  "minimum": 1
                },
                "name": {
                  "type": "string"
                },
                "world": {
                  "type": "string",
                  "enum": [
                    "light",
                    "dark"
                  ]
                }
              }
            }
          },
          "nodeItem": {
            "type": "string"
          },
          "nodeAddress": {
            "type": [
              "string",
              "array"
            ],
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "requires": {
            "type": "array",
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "locks": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "type": "object",
              "required": [
                "lockType",
                "unlock"
              ],
              "additionalProperties": false,
              "properties": {
                "lockType": {
                  "type": "string",
                  "enum": [
                    "bossFight",
                    "cutscene",
                    "gameFlag",
                    "killEnemies",
                    "lockedDoor",
                    "permanent",
                    "triggeredEvent"
                  ]
                },
                "lock": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "$ref": "z3-requirement.schema.json"
                  }
                },
                "unlock": {
                  "type": [
                    "array",
                    "null"
                  ],
                  "items": {
                    "$ref": "z3-requirement.schema.json"
                  }
                },
                "note": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              }
            }
          },
          "view": {
            "type": [
              "array",
              "null"
            ],
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "yields": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "locationName",
          "itemLocation",
          "item",
          "itemAddress"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "locationName": {
            "type": "string"
          },
          "itemLocation": {
            "type": "integer",
            "minimum": 1
          },
          "item": {
            "type": "string"
          },
          "itemAddress": {
            "type": [
              "string",
              "array"
            ],
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "lockedDoors": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "locationName",
          "doorPosition",
          "doorLocation",
          "keyType"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "integer",
            "minimum": 1
          },
          "locationName": {
            "type": "string"
          },
          "doorPosition": {
            "type": "string",
            "enum": [
              "north",
              "south",
              "east",
              "west",
              "middle"
            ]
          },
          "doorLocation": {
            "type": "integer",
            "minimum": 1
          },
          "keyType": {
            "type": "string",
            "enum": [
              "big",
              "small",
              "bomb",
              "bomb, boots",
              "boots"
            ]
          },
          "subArea": {
            "type": "string"
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          }
        }
      }
    },
    "obstacles": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "id",
          "note"
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "strats": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "link",
          "name",
          "requires"
        ],
        "additionalProperties": false,
        "properties": {
          "link": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "name": {
            "type": "string"
          },
          "requires": {
            "type": "array",
            "items": {
              "$ref": "z3-requirement.schema.json"
            }
          },
          "notable": {
            "type": "boolean"
          },
          "collectsItems": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "setsFlags": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "clearsObstacles": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string"
            }
          },
          "unlocksDoor": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "integer",
              "minimum": 1
            }
          },
          "world": {
            "type": "string",
            "enum": [
              "light",
              "dark",
              "any"
            ]
          },
          "fromWorld": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "toWorld": {
            "type": "string",
            "enum": [
              "light",
              "dark"
            ]
          },
          "isBunny": {
            "type": "string",
            "enum": [
              "yes",
              "no",
              "any"
            ]
          },
          "setsFollower": {
            "type": "string",
            "enum": [
              "None",
              "Zelda",
              "Old Man",
              "Blind",
              "Dwarf",
              "Purple Chest",
              "Big Bomb"
            ]
          },
          "FollowerComplete": {
            "type": "string",
            "enum": [
              "Zelda",
              "Old Man",
              "Blind",
              "Dwarf",
              "Purple Chest",
              "Big Bomb"
            ]
          },
          "exitState": {
            "type": "object",
            "required": [
              "state",
              "type"
            ],
            "additionalProperties": false,
            "properties": {
              "state": {
                "type": "string",
                "enum": [
                  "event"
                ]
              },
              "type": {
                "type": "string"
              }
            }
          },
          "note": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "devNote": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    }
  },
  "allOf": [
    {
      "if": {
        "required": [
          "roomType"
        ],
        "properties": {
          "roomType": {
            "const": "Overworld"
          }
        }
      },
      "then": {
        "properties": {
          "nodes": {
            "items": {
              "required": [
                "world"
              ]
            }
          },
          "strats": {
            "items": {
              "oneOf": [
                {
                  "required": [
                    "world"
                  ]
                },
                {
                  "required": [
                    "fromWorld",
                    "toWorld"
                  ]
                }
              ]
            }
          }
        }
      },
      "else": {
        "properties": {
          "nodes": {
            "items": {
              "required": [
                "nodeType"
              ]
            }
          }
        }
      }
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/35 Lake Hylia.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 35,
  "name": "Lake Hylia",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Northwest Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [8, 21]}
      ],
      "entrances": [
        {
          "id": 1,
          "name": "Lake Hylia Fortune Teller",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Lake Hylia Shop",
          "world": "light"
        },
        {
          "id": 3,
          "name": "Ice Lake Shop",
          "world": "dark"
        }
      ]
    },
    {
      "id": 2,
      "name": "Northeast Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [57, 59]}
      ]
    },
    {
      "id": 3,
      "name": "Southeast Area",
      "world": "both",
      "transitions": [
        {"edge": "east", "span": [55.5, 61]}
      ]
    },
    {
      "id": 4,
      "name": "Southwest Area",
      "world": "both",
      "transitions": [
        {"edge": "west", "span": [56, 61]}
      ]
    },
    {
      "id": 5,
      "name": "Southwest Bombable Entrance",
      "world": "light",
      "entrances": [
        {
          "id": 1,
          "name": "Mini Moldorm Cave Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 6,
      "name": "Water",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [51.5, 54.5], "terrain": "water"},
        {"edge": "east", "span": [50.5, 53.5], "terrain": "water"}
      ],
      "teleports": [
        {
          "id": 1,
          "name": "Lake Hylia Whirlpool",
          "world": "light"
        }
      ]
    },
    {
      "id": 7,
      "name": "Lake Hylia Main Island",
      "world": "both",
      "entrances": [
        {
          "id": 1,
          "name": "Lake Hylia Great Fairy",
          "world": "light"
        },
        {
          "id": 2,
          "name": "Ice Palace Entrance",
          "world": "dark"
        }
      ]
    },
    {
      "id": 8,
      "name": "Lake Hylia Small Island",
      "world": "both"
    }
  ],
  "items": [
    {
      "id": 1,
      "locationName": "Lake Hylia Island Item",
      "itemLocation": 3,
      "world": "light",
      "item": "PieceOfHeart",
      "itemAddress": "0x180144"
    }
  ],
  "lockedDoors": [
    {
      "id": 1,
      "locationName": "Southwest Bombable Wall",
      "world": "light",
      "doorPosition": "north",
      "doorLocation": 4,
      "keyType": "bomb"
    }
  ],
  "strats": [
    {
      "link": [1, 6],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [2, 6],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [3, 4],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [3, 6],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [4, 3],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [4, 4],
      "name": "Base - Bomb Wall",
      "world": "light",
      "requires": [
        {"bombs": 1}
      ],
      "unlocksDoor": [1]
    },
    {
      "link": [4, 5],
      "name": "Base - Already Opened",
      "world": "light",
      "requires": [
        {"unlockDoor": 1}
      ]
    },
    {
      "link": [4, 6],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [5, 4],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [6, 1],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [6, 2],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [6, 7],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [6, 8],
      "name": "Base",
      "world": "dark",
      "requires": [
        "Flippers",
        {"or": [
          {"combatProficiency": 2},
          {"damage": {"enemy": "Zirro (Green)", "count": 1}}
        ]}
      ],
      "devNote": [
        "FIXME: It looks like fake flippers wont let Link stand on the shallow water to teleport. Double check this.",
        "If that's not the case, then the whirlpool logic needs to be checked, since its surrounded by shallow water."
      ]
    },
    {
      "link": [7, 6],
      "name": "Base",
      "world": "light",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [7, 7],
      "fromWorld": "light",
      "toWorld": "dark",
      "name": "Dark World Portal",
      "requires": [
        {"glove": 2}
      ]
    },
    {
      "link": [8, 6],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [8, 8],
      "name": "Base - Collect Item",
      "world": "light",
      "requires": [],
      "collectsItems": [1]
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/07 Turtle Rock.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 5,
  "name": "Turtle Rock",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "West Edge",
      "world": "both"
    },
    {
      "id": 2,
      "name": "Raised Platform",
      "world": "both"
    },
    {
      "id": 3,
      "name": "Turtle Rock Entrance",
      "world": "dark",
      "entrances": [
        {
          "id": 1,
          "name": "Turtle Rock Entrance",
          "world": "dark"
        }
      ]
    }
  ],
  "strats": [
    {
      "link": [1, 2],
      "name": "Base",
      "world": "light",
      "requires": [
        {"glove": 2},
        {"or": [
          {"damage": {"enemy": "Deadrock", "count": 2}},
          {"combatProficiency": 2}
        ]}
      ]
    },
    {
      "link": [1, 3],
      "name": "Base",
      "world": "dark",
      "requires": [
        {"flag": "OpenedTurtleRock"}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [2, 2],
      "fromWorld": "light",
      "toWorld": "dark",
      "name": "Dark World Portal",
      "requires": [
        "Hammer"
      ]
    },
    {
      "link": [2, 2],
      "name": "Open Turtle Rock",
      "world": "dark",
      "requires": [
        {"sword": 1},
        "h_TurtleRockMedallion"
      ],
      "setsFlags": ["OpenedTurtleRock"]
    },
    {
      "link": [3, 1],
      "name": "Base",
      "world": "dark",
      "requires": []
    }
  ]
}

=== kjbranch/z3-json-data/rooms/overworld/34 Great Swamp Fairy.json
{
  "$schema": "../../schema/z3-room.schema.json",
  "id": 34,
  "name": "Great Swamp Fairy",
  "roomType": "Overworld",
  "nodes": [
    {
      "id": 1,
      "name": "Main Area",
      "world": "both",
      "transitions": [
        {"edge": "north", "span": [13, 16]},
        {"edge": "south", "span": [3, 28]},
        {"edge": "west", "span": [8, 15]},
        {"edge": "west", "span": [21, 29]}
      ]
    },
    {
      "id": 2,
      "name": "Lake Transition",
      "world": "both",
      "transitions": [
        {"edge": "west", "span": [15, 21], "terrain": "water"}
      ]
    },
    {
      "id": 3,
      "name": "Light World Bombable Wall",
      "world": "light",
      "entrances": [
        {
          "id": 1,
          "name": "Swamp Great Fairy Entrance",
          "world": "light"
        }
      ]
    },
    {
      "id": 4,
      "name": "Dark World Bombable Wall",
      "world": "dark",
      "entrances": [
        {
          "id": 1,
          "name": "Hype Cave Entrance",
          "world": "dark"
        }
      ]
    }
  ],
  "lockedDoors": [
    {
      "id": 1,
      "locationName": "Bombable Wall",
      "world": "light",
      "doorPosition": "north",
      "doorLocation": 1,
      "keyType": "bomb"
    },
    {
      "id": 2,
      "locationName": "Bombable Wall",
      "world": "dark",
      "doorPosition": "north",
      "doorLocation": 1,
      "keyType": "bomb"
    }
  ],
  "strats": [
    {
      "link": [1, 1],
      "name": "Base - Bomb",
      "world": "light",
      "requires": [
        {"bombs": 1}
      ],
      "unlocksDoor": [1]
    },
    {
      "link": [1, 1],
      "name": "Base - Bomb",
      "world": "dark",
      "requires": [
        {"bombs": 1}
      ],
      "unlocksDoor": [2]
    },
    {
      "link": [1, 2],
      "name": "Base",
      "world": "any",
      "requires": [
        "Flippers"
      ]
    },
    {
      "link": [1, 3],
      "name": "Base - Already Bombed",
      "world": "light",
      "requires": [
        {"unlockDoor": 1}
      ]
    },
    {
      "link": [1, 4],
      "name": "Base - Already Bombed",
      "world": "dark",
      "requires": [
        {"unlockDoor": 2}
      ]
    },
    {
      "link": [2, 1],
      "name": "Base",
      "world": "any",
      "requires": []
    },
    {
      "link": [3, 1],
      "name": "Base",
      "world": "light",
      "requires": []
    },
    {
      "link": [4, 1],
      "name": "Base",
      "world": "dark",
      "requires": []
    }
  ]
}
